version: "3.9"

services:
  students-api:
    build: .
    container_name: students-api-container
    ports:
      - "8082:8082"
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
    environment:
      - ENV=dev
      - STORAGE_PATH=storage/storage.db 